export const SYSTEM_NAME = 'Parking System'

const BACKEND = '/backend/'
export const USER_PATH = BACKEND + 'user'
export const PARKING_PATH = BACKEND + 'parking'
export const DASHBOARD_PATH = BACKEND + 'dashboard'
export const CUSTOMER_PATH = BACKEND + 'customer'
export const REPORT_PATH = BACKEND + 'report'
export const BORROW_LIST_PATH = BACKEND + 'borrow_list'
export const EQUIPMENT_PATH = BACKEND + 'equipment'